name: ocr_text_recognition
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  camera: ^0.10.3+1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_core: ^2.7.0 
  google_ml_kit: ^0.13.0
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  image_picker: ^0.8.6+3
  intl: ^0.18.0
  path: null
  path_provider: ^2.0.13
  clipboard: ^0.1.3
  cloud_firestore: ^4.4.4

  flutter:
    sdk: flutter


  # google_mlkit_text_recognition: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:

  uses-material-design: true
