// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQQXssCY31ziwiDq0QCt4Xm-RFtN_ut0E',
    appId: '1:819361355908:web:9fc2c30c9374383d9e0ad1',
    messagingSenderId: '819361355908',
    projectId: 'ocr-text-recognition-ee4d9',
    authDomain: 'ocr-text-recognition-ee4d9.firebaseapp.com',
    storageBucket: 'ocr-text-recognition-ee4d9.appspot.com',
    measurementId: 'G-RZ99D5ERBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-3B-tBuW6jk-VvFiUFAfq4J_K3Tc0ySQ',
    appId: '1:819361355908:android:5605e633d8ab8c119e0ad1',
    messagingSenderId: '819361355908',
    projectId: 'ocr-text-recognition-ee4d9',
    storageBucket: 'ocr-text-recognition-ee4d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRIF8caI71VPHdNrY6wpkIfnq5siJlNOU',
    appId: '1:819361355908:ios:4b935dea1f0db0049e0ad1',
    messagingSenderId: '819361355908',
    projectId: 'ocr-text-recognition-ee4d9',
    storageBucket: 'ocr-text-recognition-ee4d9.appspot.com',
    iosClientId: '819361355908-di5e9vtglhd0uh93rmcaj7g3gubg592h.apps.googleusercontent.com',
    iosBundleId: 'com.example.ocrTextRecognition',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRIF8caI71VPHdNrY6wpkIfnq5siJlNOU',
    appId: '1:819361355908:ios:4b935dea1f0db0049e0ad1',
    messagingSenderId: '819361355908',
    projectId: 'ocr-text-recognition-ee4d9',
    storageBucket: 'ocr-text-recognition-ee4d9.appspot.com',
    iosClientId: '819361355908-di5e9vtglhd0uh93rmcaj7g3gubg592h.apps.googleusercontent.com',
    iosBundleId: 'com.example.ocrTextRecognition',
  );
}
